language: java
# use Java 8
jdk:
- oraclejdk9

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: true

before_install:
  - chmod +x mvnw

script:
- ./mvnw clean install -B
